name: "Runs load test"
runs:
  using: "composite"
  steps:
    - name: Install Load testing tool k6 
      shell: bash 
      run: |
        echo "Installing k6 load tool"
        sudo apt-get update && sudo apt-get install -y gnupg2 ca-certificates
        curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/k6.gpg
        sudo apt-get update
        sudo apt-get install -y k6
        k6 version

