name: CI-kind

on: 
  pull_request:
     branches:
       - msin

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: repository
        uses: actions/checkout@v3
      
      - name: docker-setup
        uses: docker/setup-buildx-action@v2

      - name: kind-installation
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      
      - name: create-kind-cluster-multinode
        run: |
          cat <<EOF > kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
            - role: worker
          EOF
          kind create cluster --name ci-multinode-cluster --config kind-config.yaml
          kind cluster-info
          kubectl get nodes
 
      - name: test the pods
        run: |
           kubectl get pods  -A 
           echo "Kind cluster with multi-node is created successfully"

        